sudo: required
language: node_js
node_js:
  - 16
dist: xenial

jobs:
  include:
    - stage: Deploying demo server & running tests
      script: xvfb-run --server-args="-screen 0 1024x768x24" make test
      script: npm run test

before_install:
  - npm install
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:39500 &
addons:
  chrome: stable
services:
  - xvfb
cache:
   directories:
     - node_modules
env:
  - APPLITOOLS_API_KEY=<APPLITOOLS_API_KEY>
  - APPLITOOLS_BATCH_SEQUENCE=<APPLITOOLS_BATCH_SEQUENCE>