sudo: required
language: node_js
node_js:
  - 16
dist: xenial

jobs:
  include:
    - stage: Deploying demo server & running tests
      script: xvfb-run --server-args="-screen 0 1024x768x24" make test
      script: npm run url-monitor

before_install:
  - npm install
  - npm install encoding@^0.1.0
  - npm install bufferutil@^4.0.1
  - npm install utf-8-validate@^5.0.2
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:39500 &
addons:
  chrome: stable
services:
  - xvfb
cache:
   directories:
     - node_modules
env:
  - APPLITOOLS_API_KEY='IVATJb9JJqGfzLDJ6p3eWtU4hUsOO5rAFmciVSi4qtk110'