name: Run Applitools

on: 
   # schedule:
   #     - cron:  '*/15 * * * *'   
   # push:
   pull_request:
     types: [opened, reopened]
   workflow_dispatch:
   
env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY_DEMO_1 }}
  APPLITOOLS_BATCH_ID: ${{ github.sha }}
  APPLITOOLS_BATCH_NAME: ${{ github.workflow }} ${{ github.event_name }}:#${{ github.run_number }}
  APPLITOOLS_SERVER_URL : "https://eyesapi.applitools.com"
  APPLITOOLS_BRANCH: ${{ github.ref_name }}
  APPLITOOLS_PARENT_BRANCH: ${{ github.base_ref }}

jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: applitools-github-integration

      steps:
        - name: Notify Applitools
          uses: wei/curl@v1
          with:
           # args: -L -d -v '' -X POST "https://eyesapi.applitools.com/api/externals/github/push?apiKey=$${{secrets.APPLITOOLS_API_KEY_DEMO_1}}&CommitSha=${{github.sha}}&BranchName=${{ github.ref_name }}&ParentBranchName=${{ github.base_ref }}"
           args: -d \"\" -X POST "${{ env.APPLITOOLS_SERVER_URL }}/api/Externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/complete?apiKey=${{ env.APPLITOOLS_API_KEY }}"

        - uses: actions/checkout@v2
          with:
            ref: ${{ github.ref }}
        
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - uses: browser-actions/setup-chrome@latest
        
        - run: npm install
        
      # < to run headed>
      #  - run: |
      #     export DISPLAY=:99
      #     chromedrive & sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & npm test
        
        - run: npm test
