name: Run Applitools non-PR

on: 
   # schedule:
   #     - cron:  '*/15 * * * *'   
   # push:
   workflow_dispatch:
   
env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY_DEMO_1 }}
  APPLITOOLS_BATCH_ID: ${{ github.sha }}
  APPLITOOLS_BATCH_NAME: Run ${{ github.run_number }} ${{ github.ref_name }}
  APPLITOOLS_SERVER_URL : "https://eyesapi.applitools.com"
  APPLITOOLS_BASELINE_BRANCH: ${{ github.repository }}/${{ github.ref_name }}
  APPLITOOLS_PARENT_BRANCH: ${{ github.repository }}/${{ github.base_ref }}
  APPLITOOLS_BRANCH: ${{ github.repository }}/${{ github.ref_name }}

jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: applitools-github-integration

      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ github.ref }}
        
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        # - uses: browser-actions/setup-chrome@latest
        #  with:
        #    chrome-version: stable
        
        - run: npm ci
        - run: npm install chromedriver --detect_chromedriver_version --no-save
        
      # < to run headed>
      #  - run: |
      #     export DISPLAY=:99
      #     chromedrive & sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & npm test
        
        - run: npm test
