on: 
    push:
      branches: [ main ]
    workflow_dispatch:

jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: url-monitor-is-my-name

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - uses: browser-actions/setup-chrome@latest
        - run: INCLUDE_CHROMIUM=true npm install
        #/opt/hostedtoolcache/chromium/latest/x64/
        - run: set CHROMIUM_BIN=$(which chrome) && echo $CHROMIUM_BIN && echo $PATH && export PATH="$CHROMIUM_BIN:$PATH" && echo $PATH && npm test
          env:
            APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
