on: 
   # push:
   #   branches: [ main ]
   # schedule:
   #     - cron:  '*/15 * * * *'   
   # pull_request:
   #  types: [opened, reopened]
   workflow_dispatch:

jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: Master-applitools-github-integration

      steps:
        - name: curl
          uses: wei/curl@v1
          with:
           args: -L -d '' -X POST "$APPLITOOLS_SERVER_URL/api/externals/github/push?apiKey=$${{secrets.APPLITOOLS_API_KEY_DEMO_1}}&CommitSha=${{github.sha}}&BranchName=$APPLITOOLS_BRANCH&ParentBranchName=$APPLITOOLS_PARENT_BRANCH"
        - uses: actions/checkout@v2
          with:
            ref: main
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - uses: browser-actions/setup-chrome@latest
        - run: npm install
        
      # < to run headed>
      #  - run: |
      #     export DISPLAY=:99
      #     chromedrive & sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & npm test
        
        - run: npm test
        
          env:
            APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY_DEMO_1 }}
            APPLITOOLS_BATCH_ID: ${{ github.sha }}
            APPLITOOLS_SERVER_URL : "eyesapi.applitools.com"
            APPLITOOLS_BRANCH: ${{ github.ref }}
            APPLITOOLS_PARENT_BRANCH: ${{ github.base_ref }}
