on: 
    push:
      branches: [ main ]
    workflow_dispatch:

jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: url-monitor-is-my-name

      steps:
        - name: add Applitools API key
          env: 
            key: ${{ secrets.APPLITOOLS_API_KEY }}
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'

        - run: npm install
        - run: npm test
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
