on: 
    push:
      branches: [ main ]
    workflow_dispatch:

jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: url-monitor-is-my-name

      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - env: 
            key: ${{ secrets.APPLITOOLS_API_KEY }}
        - run: npm install
        - run: npm test
