on: [push]
  workflow_dispatch:

jobs:
  run_monitor_job:
    runs-on: ubuntu-latest
    name: url-monitor-is-my-name

  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm test