name: Inform Applitools of PR

on: 
   # schedule:
   #     - cron:  '*/15 * * * *'   
   #  push:
     pull_request:
      types: [edited, opened, reopened]
   # workflow_dispatch:
   
env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY_DEMO_1 }}
  APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha || github.sha }}
  APPLITOOLS_BATCH_NAME: ${{ github.head_ref || github.ref_name }} ${{ github.event.pull_request.head.sha || github.sha }} ${{ github.event_name }}
  APPLITOOLS_SERVER_URL : "https://eyesapi.applitools.com"
  APPLITOOLS_BRANCH: ${{ github.repository }}/${{ github.head_ref || github.ref_name}}
  # APPLITOOLS_PARENT_BRANCH: ${{ github.repository }}/${{ github.base_ref }}
  REPOSITORY: ${{ github.repository }}
  ACTION_REF: ${{ github.action_ref }}
  BASE_REF: ${{ github.base_ref }}
  HEAD_REF: ${{ github.head_ref }}
  REF: ${{ github.ref }}
  REF_NAME: ${{ github.ref_name }}
  RUN_ID: ${{ github.run_id }}
  SHA: ${{ github.sha }}
  HEAD.SHA: ${{ github.event.pull_request.head.sha }}
  EVENT_NAME: ${{ github.event_name }}


jobs:
    run-monitor-job:
      runs-on: ubuntu-latest
      name: applitools-github-integration
      
      strategy:
        matrix:
          node-version: [16.x]

      steps:
        - name: Notify Applitools
          if: github.event_name != 'pull_request'
          uses: wei/curl@v1
          with:
            args: -L -d -v '' -X POST "${{env.APPLITOOLS_SERVER_URL}}/api/Externals/github/push?apiKey=$${{secrets.APPLITOOLS_API_KEY_DEMO_1}}&CommitSha=${{ env.APPLITOOLS_BATCH_ID }}&BranchName=${{ env.APPLITOOLS_BRANCH }}"

